import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useLanguage } from "@/contexts/LanguageContext";
import { trpc } from "@/lib/trpc";
import { FileUp, Paperclip, Stethoscope } from "lucide-react";
import { useState } from "react";

export default function MedicalRecordsPage() {
  const { isArabic, direction } = useLanguage();
  const [visitId, setVisitId] = useState("");
  const [patientId, setPatientId] = useState("");
  const [file, setFile] = useState<File | null>(null);
  const [visitForm, setVisitForm] = useState({ appointmentId: "", doctorId: "", chiefComplaint: "", diagnosis: "", medications: "", followUpPlan: "", visitNotes: "" });
  const visits = trpc.medicalVisits.listByPatient.useQuery({ patientId: Number(patientId) }, { enabled: Number(patientId) > 0 });
  const attachments = trpc.medicalAttachments.listByVisit.useQuery({ visitId: Number(visitId), patientId: Number(patientId) }, { enabled: Number(visitId) > 0 && Number(patientId) > 0 });
  const upload = trpc.medicalAttachments.upload.useMutation({ onSuccess: () => { setFile(null); void attachments.refetch(); } });
  const createVisit = trpc.medicalVisits.create.useMutation({ onSuccess: () => void visits.refetch() });
  const updateVisit = (key: keyof typeof visitForm, value: string) => setVisitForm(current => ({ ...current, [key]: value }));

  const submitUpload = async (event: React.FormEvent) => {
    event.preventDefault();
    if (!file || file.size > 10 * 1024 * 1024) return;
    const dataBase64 = await new Promise<string>((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(String(reader.result).split(",")[1] ?? "");
      reader.onerror = reject;
      reader.readAsDataURL(file);
    });
    upload.mutate({ visitId: Number(visitId), patientId: Number(patientId), fileName: file.name, mimeType: file.type as "application/pdf" | "image/jpeg" | "image/png" | "image/webp", dataBase64, sizeBytes: file.size });
  };

  const submitVisit = (event: React.FormEvent) => {
    event.preventDefault();
    createVisit.mutate({ appointmentId: Number(visitForm.appointmentId), patientId: Number(patientId), doctorId: Number(visitForm.doctorId), chiefComplaint: visitForm.chiefComplaint, diagnosis: visitForm.diagnosis, medications: visitForm.medications, followUpPlan: visitForm.followUpPlan, visitNotes: visitForm.visitNotes });
  };

  const branchScopeDenied = Boolean(visits.error?.message?.toLowerCase().includes("branch scope"));
  const historyContent = visits.isLoading ? <p className="text-sm text-slate-400">{isArabic ? "جارٍ التحميل..." : "Loading..."}</p> : visits.error ? <p className="text-sm text-red-600">{branchScopeDenied ? (isArabic ? "هذا السجل مرتبط بفرع غير مسند إلى حسابك." : "This medical history belongs to a branch not assigned to your account.") : (isArabic ? "لا تملك صلاحية عرض هذا السجل الطبي." : "You do not have permission to view this medical history.")}</p> : (visits.data ?? []).length === 0 ? <p className="text-sm text-slate-400">{isArabic ? "لا توجد زيارات مسجلة" : "No visits recorded"}</p> : <div className="space-y-3">{(visits.data ?? []).map(visit => <div key={visit.id} className="rounded-xl border border-slate-100 p-4"><div className="flex items-start justify-between gap-4"><p className="font-semibold">{isArabic ? "زيارة طبية" : "Medical visit"} #{visit.id}</p><p className="text-xs text-slate-400">{new Date(visit.recordedAt).toLocaleString(isArabic ? "ar-EG" : "en-US")}</p></div><div className="mt-3 grid gap-3 text-sm md:grid-cols-2"><p><span className="text-slate-400">{isArabic ? "الشكوى:" : "Complaint:"}</span> {visit.chiefComplaint || "—"}</p><p><span className="text-slate-400">{isArabic ? "التشخيص:" : "Diagnosis:"}</span> {visit.diagnosis || "—"}</p><p><span className="text-slate-400">{isArabic ? "الأدوية:" : "Medications:"}</span> {visit.medications || "—"}</p><p><span className="text-slate-400">{isArabic ? "المتابعة:" : "Follow-up:"}</span> {visit.followUpPlan || "—"}</p><p className="md:col-span-2"><span className="text-slate-400">{isArabic ? "ملاحظات:" : "Notes:"}</span> {visit.visitNotes || "—"}</p><p className="text-xs text-slate-400 md:col-span-2">{isArabic ? "الطبيب رقم" : "Doctor ID"}: {visit.doctorId} · {isArabic ? "الموعد رقم" : "Appointment ID"}: {visit.appointmentId}</p></div></div>)}</div>;

  return <DashboardLayout><div dir={direction} className="min-h-screen bg-[#f7fafc] p-4 text-slate-900 sm:p-8"><div className="mx-auto max-w-5xl space-y-6"><header><p className="text-sm font-medium text-teal-700">{isArabic ? "الملف الطبي" : "Medical records"}</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">{isArabic ? "الزيارات والمرفقات" : "Visits and attachments"}</h1><p className="mt-2 text-sm text-slate-500">{isArabic ? "سجل الشكوى والتشخيص والمتابعة واربط المستندات بالزيارة المحددة." : "Record clinical details and link documents to a specific visit."}</p></header>
    <Card className="border-0 bg-white shadow-[0_12px_35px_rgba(15,23,42,0.05)]"><CardHeader><CardTitle className="flex items-center gap-2"><Stethoscope className="h-5 w-5 text-teal-700" />{isArabic ? "تسجيل زيارة طبية" : "Record medical visit"}</CardTitle></CardHeader><CardContent><form onSubmit={submitVisit} className="grid gap-4 md:grid-cols-2"><Input required type="number" min="1" placeholder={isArabic ? "رقم المريض" : "Patient ID"} value={patientId} onChange={event => setPatientId(event.target.value)} /><Input required type="number" min="1" placeholder={isArabic ? "رقم الموعد" : "Appointment ID"} value={visitForm.appointmentId} onChange={event => updateVisit("appointmentId", event.target.value)} /><Input required type="number" min="1" placeholder={isArabic ? "رقم الطبيب" : "Doctor ID"} value={visitForm.doctorId} onChange={event => updateVisit("doctorId", event.target.value)} /><Input placeholder={isArabic ? "الشكوى الرئيسية" : "Chief complaint"} value={visitForm.chiefComplaint} onChange={event => updateVisit("chiefComplaint", event.target.value)} /><Textarea className="md:col-span-2" placeholder={isArabic ? "التشخيص" : "Diagnosis"} value={visitForm.diagnosis} onChange={event => updateVisit("diagnosis", event.target.value)} /><Textarea placeholder={isArabic ? "الأدوية" : "Medications"} value={visitForm.medications} onChange={event => updateVisit("medications", event.target.value)} /><Textarea placeholder={isArabic ? "خطة المتابعة" : "Follow-up plan"} value={visitForm.followUpPlan} onChange={event => updateVisit("followUpPlan", event.target.value)} /><Textarea className="md:col-span-2" placeholder={isArabic ? "ملاحظات الزيارة" : "Visit notes"} value={visitForm.visitNotes} onChange={event => updateVisit("visitNotes", event.target.value)} /><Button type="submit" disabled={createVisit.isPending} className="w-fit bg-teal-700 text-white hover:bg-teal-800">{createVisit.isPending ? (isArabic ? "جارٍ الحفظ..." : "Saving...") : (isArabic ? "حفظ الزيارة" : "Save visit")}</Button></form>{createVisit.error && <p className="mt-3 text-sm text-red-600">{isArabic ? "تعذر حفظ الزيارة، تأكد من أرقام الموعد والمريض والطبيب." : "Could not save the visit. Check the appointment, patient, and doctor IDs."}</p>}</CardContent></Card>
    {Number(patientId) > 0 && <Card className="border-0 bg-white"><CardHeader><CardTitle>{isArabic ? "تاريخ زيارات المريض" : "Patient visit history"}</CardTitle></CardHeader><CardContent>{historyContent}</CardContent></Card>}
    <Card className="border-0 bg-white shadow-[0_12px_35px_rgba(15,23,42,0.05)]"><CardHeader><CardTitle className="flex items-center gap-2"><Paperclip className="h-5 w-5 text-teal-700" />{isArabic ? "رفع مرفق للزيارة" : "Upload visit attachment"}</CardTitle></CardHeader><CardContent><form onSubmit={submitUpload} className="grid gap-4 md:grid-cols-2"><Input required type="number" min="1" placeholder={isArabic ? "رقم الزيارة" : "Visit ID"} value={visitId} onChange={event => setVisitId(event.target.value)} /><Input required type="number" min="1" placeholder={isArabic ? "رقم المريض" : "Patient ID"} value={patientId} onChange={event => setPatientId(event.target.value)} /><Input required className="md:col-span-2" type="file" accept="application/pdf,image/jpeg,image/png,image/webp" onChange={event => setFile(event.target.files?.[0] ?? null)} /><p className="text-xs text-slate-500 md:col-span-2">{isArabic ? "الأنواع المسموحة: PDF وJPG وPNG وWEBP، بحد أقصى 10 ميجابايت." : "Allowed: PDF, JPG, PNG, and WEBP, up to 10 MB."}</p><Button type="submit" disabled={!file || upload.isPending} className="w-fit gap-2 bg-teal-700 text-white hover:bg-teal-800"><FileUp className="h-4 w-4" />{upload.isPending ? (isArabic ? "جارٍ الرفع..." : "Uploading...") : (isArabic ? "رفع المرفق" : "Upload")}</Button></form>{upload.isSuccess && <p className="mt-4 text-sm text-emerald-700">{isArabic ? "تم ربط المرفق بالزيارة بنجاح." : "Attachment linked to the visit successfully."}</p>}{upload.error && <p className="mt-4 text-sm text-red-600">{isArabic ? "تعذر رفع المرفق أو أن الزيارة لا تخص المريض المحدد." : "Upload failed or the visit does not belong to the selected patient."}</p>}{Number(visitId) > 0 && Number(patientId) > 0 && <div className="mt-6 border-t border-slate-100 pt-4"><p className="mb-3 text-sm font-medium">{isArabic ? "مرفقات الزيارة" : "Visit attachments"}</p>{attachments.isLoading ? <p className="text-sm text-slate-400">{isArabic ? "جارٍ التحميل..." : "Loading..."}</p> : (attachments.data ?? []).length === 0 ? <p className="text-sm text-slate-400">{isArabic ? "لا توجد مرفقات بعد" : "No attachments yet"}</p> : <div className="space-y-2">{(attachments.data ?? []).map(item => <a key={item.id} href={item.storageUrl} target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-lg bg-slate-50 px-3 py-2 text-sm text-teal-800 hover:bg-teal-50"><span>{item.fileName}</span><span className="text-xs text-slate-400">{item.mimeType}</span></a>)}</div>}</div>}</CardContent></Card></div></div></DashboardLayout>;
}
