import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { useLanguage } from "@/contexts/LanguageContext";
import { trpc } from "@/lib/trpc";
import { BarChart3, CalendarCheck, CircleDollarSign, UserPlus } from "lucide-react";
import { useState } from "react";

export default function ReportsPage() {
  const { isArabic, direction } = useLanguage();
  const [branchId, setBranchId] = useState("");
  const [from, setFrom] = useState("");
  const [to, setTo] = useState("");
  const branches = trpc.branches.list.useQuery();
  const report = trpc.reports.summary.useQuery({ branchId: Number(branchId) > 0 ? Number(branchId) : undefined, from: from || undefined, to: to || undefined });

  return <DashboardLayout><div dir={direction} className="min-h-screen bg-[#f7fafc] p-4 text-slate-900 sm:p-8"><div className="mx-auto max-w-6xl space-y-6">
    <header><p className="text-sm font-medium text-teal-700">{isArabic ? "التحليلات" : "Analytics"}</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">{isArabic ? "التقارير" : "Reports"}</h1><p className="mt-2 text-sm text-slate-500">{isArabic ? "تابع الحجوزات والتحصيل والمرضى الجدد حسب الفترة والفرع." : "Track bookings, collections, and new patients by period and branch."}</p></header>
    <Card className="border-0 bg-white"><CardHeader><CardTitle>{isArabic ? "فلاتر التقرير" : "Report filters"}</CardTitle></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-4"><select className="h-10 rounded-md border border-slate-200 bg-white px-3 text-sm" value={branchId} onChange={event => setBranchId(event.target.value)}><option value="">{isArabic ? "كل الفروع" : "All branches"}</option>{(branches.data ?? []).map(branch => <option key={branch.id} value={branch.id}>{isArabic ? branch.nameAr : branch.nameEn}</option>)}</select><Input type="date" value={from} onChange={event => setFrom(event.target.value)} /><Input type="date" value={to} onChange={event => setTo(event.target.value)} /><Button variant="outline" onClick={() => void report.refetch()}>{isArabic ? "تحديث التقرير" : "Refresh report"}</Button></div></CardContent></Card>
    {report.isLoading ? <p className="text-sm text-slate-400">{isArabic ? "جارٍ التحميل..." : "Loading..."}</p> : report.error ? <p className="text-sm text-red-600">{isArabic ? "تعذر تحميل التقرير." : "Could not load the report."}</p> : <div className="space-y-4"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={<CalendarCheck className="h-5 w-5" />} label={isArabic ? "الحجوزات" : "Bookings"} value={report.data?.bookings ?? 0} /><Metric icon={<BarChart3 className="h-5 w-5" />} label={isArabic ? "وصلوا" : "Arrived"} value={report.data?.arrived ?? 0} /><Metric icon={<BarChart3 className="h-5 w-5" />} label={isArabic ? "المكتملة" : "Completed"} value={report.data?.completed ?? 0} /><Metric icon={<BarChart3 className="h-5 w-5" />} label={isArabic ? "الملغاة / لم يحضر" : "Cancelled / no-show"} value={`${report.data?.cancelled ?? 0} / ${report.data?.noShow ?? 0}`} /><Metric icon={<CircleDollarSign className="h-5 w-5" />} label={isArabic ? "التحصيل" : "Collections"} value={`${report.data?.collections ?? "0.00"} EGP`} /><Metric icon={<CircleDollarSign className="h-5 w-5" />} label={isArabic ? "الأرصدة المستحقة" : "Outstanding"} value={`${report.data?.outstanding ?? "0.00"} EGP`} /><Metric icon={<CircleDollarSign className="h-5 w-5" />} label={isArabic ? "الاستردادات" : "Refunds"} value={`${report.data?.refunds ?? "0.00"} EGP`} /><Metric icon={<UserPlus className="h-5 w-5" />} label={isArabic ? "مرضى جدد" : "New patients"} value={report.data?.newPatients ?? 0} /></div><div className="grid gap-4 md:grid-cols-2"><Card className="border-0 bg-white"><CardHeader><CardTitle>{isArabic ? "التحصيل حسب طريقة الدفع" : "Collections by method"}</CardTitle></CardHeader><CardContent className="space-y-2">{Object.entries(report.data?.paymentMethods ?? {}).length === 0 ? <p className="text-sm text-slate-400">{isArabic ? "لا توجد دفعات في الفترة." : "No payments in this period."}</p> : Object.entries(report.data?.paymentMethods ?? {}).map(([method, amount]) => <div key={method} className="flex justify-between text-sm"><span>{method}</span><strong>{Number(amount).toFixed(2)} EGP</strong></div>)}</CardContent></Card><Card className="border-0 bg-white"><CardHeader><CardTitle>{isArabic ? "أداء الأطباء" : "Doctor performance"}</CardTitle></CardHeader><CardContent className="space-y-2">{(report.data?.doctorPerformance ?? []).length === 0 ? <p className="text-sm text-slate-400">{isArabic ? "لا توجد حجوزات." : "No appointments."}</p> : (report.data?.doctorPerformance ?? []).map(item => <div key={item.doctorId} className="flex justify-between text-sm"><span>{item.doctorName}</span><span>{item.completed}/{item.bookings} · {isArabic ? "لم يحضر" : "no-show"}: {item.noShow}</span></div>)}</CardContent></Card></div></div>}
  </div></div></DashboardLayout>;
}

function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: React.ReactNode }) { return <Card className="border-0 bg-white shadow-[0_12px_35px_rgba(15,23,42,0.05)]"><CardContent className="p-5"><div className="flex items-center justify-between"><span className="text-sm text-slate-500">{label}</span><span className="text-teal-700">{icon}</span></div><p className="mt-4 text-2xl font-semibold">{value}</p></CardContent></Card>; }
