import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { useLanguage } from "@/contexts/LanguageContext";
import { trpc } from "@/lib/trpc";
import { Plus, Tags } from "lucide-react";
import { useState } from "react";

export default function ServicesPage() {
  const { isArabic, direction } = useLanguage();
  const services = trpc.services.list.useQuery();
  const branches = trpc.branches.list.useQuery();
  const [serviceForm, setServiceForm] = useState({ nameAr: "", nameEn: "", defaultPrice: "" });
  const [editingServiceId, setEditingServiceId] = useState<number | null>(null);
  const [priceForm, setPriceForm] = useState({ branchId: "", serviceId: "", price: "" });
  const create = trpc.services.create.useMutation({ onSuccess: () => { setServiceForm({ nameAr: "", nameEn: "", defaultPrice: "" }); void services.refetch(); } });
  const savePrice = trpc.services.saveBranchPrice.useMutation({ onSuccess: () => { setPriceForm(current => ({ ...current, price: "" })); } });
  const update = trpc.services.update.useMutation({ onSuccess: () => { setEditingServiceId(null); setServiceForm({ nameAr: "", nameEn: "", defaultPrice: "" }); void services.refetch(); } });
  const branchServices = trpc.services.listByBranchForManagement.useQuery({ branchId: Number(priceForm.branchId) }, { enabled: Number(priceForm.branchId) > 0 });

  return <DashboardLayout><div dir={direction} className="min-h-screen bg-[#f7fafc] p-4 text-slate-900 sm:p-8"><div className="mx-auto max-w-6xl space-y-6"><header className="border-b border-slate-200 pb-6"><p className="text-sm font-medium text-teal-700">{isArabic ? "الخدمات والأسعار" : "Services & pricing"}</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">{isArabic ? "خدمات الفروع" : "Branch services"}</h1><p className="mt-2 text-sm text-slate-500">{isArabic ? "أنشئ الخدمات وحدد سعرها حسب الفرع قبل إصدار الفاتورة." : "Create services and assign branch-specific prices before invoicing."}</p></header>

  <div className="grid gap-6 lg:grid-cols-2"><Card className="border-0 bg-white"><CardHeader><CardTitle className="flex items-center gap-2"><Plus className="h-5 w-5 text-teal-700" />{isArabic ? "خدمة جديدة" : "New service"}</CardTitle></CardHeader><CardContent><form className="grid gap-3" onSubmit={event => { event.preventDefault(); if (editingServiceId) update.mutate({ id: editingServiceId, ...serviceForm }); else create.mutate({ ...serviceForm, defaultPrice: serviceForm.defaultPrice }); }}><Input required placeholder={isArabic ? "اسم الخدمة بالعربية" : "Service name in Arabic"} value={serviceForm.nameAr} onChange={event => setServiceForm(current => ({ ...current, nameAr: event.target.value }))} /><Input required placeholder={isArabic ? "اسم الخدمة بالإنجليزية" : "Service name in English"} value={serviceForm.nameEn} onChange={event => setServiceForm(current => ({ ...current, nameEn: event.target.value }))} /><Input required type="number" min="0" step="0.01" placeholder={isArabic ? "السعر الافتراضي" : "Default price"} value={serviceForm.defaultPrice} onChange={event => setServiceForm(current => ({ ...current, defaultPrice: event.target.value }))} /><Button disabled={create.isPending} className="w-fit bg-teal-700 text-white hover:bg-teal-800">{(create.isPending || update.isPending) ? (isArabic ? "جارٍ الحفظ..." : "Saving...") : (editingServiceId ? (isArabic ? "حفظ التعديل" : "Save changes") : (isArabic ? "حفظ الخدمة" : "Save service"))}</Button>{editingServiceId && <Button type="button" variant="ghost" onClick={() => { setEditingServiceId(null); setServiceForm({ nameAr: "", nameEn: "", defaultPrice: "" }); }}>{isArabic ? "إلغاء التعديل" : "Cancel edit"}</Button>}{(create.error || update.error) && <p className="text-sm text-red-600">{isArabic ? "تعذر حفظ الخدمة." : "Could not save the service."}</p>}{create.error && <p className="text-sm text-red-600">{isArabic ? "تعذر إنشاء الخدمة." : "Could not create the service."}</p>}</form></CardContent></Card>

  <Card className="border-0 bg-white"><CardHeader><CardTitle className="flex items-center gap-2"><Tags className="h-5 w-5 text-teal-700" />{isArabic ? "سعر الخدمة في فرع" : "Branch price"}</CardTitle></CardHeader><CardContent><form className="grid gap-3" onSubmit={event => { event.preventDefault(); savePrice.mutate({ branchId: Number(priceForm.branchId), serviceId: Number(priceForm.serviceId), price: priceForm.price, isActive: true }); }}><select required className="h-10 rounded-md border border-slate-200 bg-white px-3 text-sm" value={priceForm.branchId} onChange={event => setPriceForm(current => ({ ...current, branchId: event.target.value }))}><option value="">{isArabic ? "اختر الفرع" : "Select branch"}</option>{(branches.data ?? []).map(branch => <option key={branch.id} value={branch.id}>{isArabic ? branch.nameAr : branch.nameEn}</option>)}</select><select required className="h-10 rounded-md border border-slate-200 bg-white px-3 text-sm" value={priceForm.serviceId} onChange={event => setPriceForm(current => ({ ...current, serviceId: event.target.value }))}><option value="">{isArabic ? "اختر الخدمة" : "Select service"}</option>{(services.data ?? []).filter(service => service.isActive).map(service => <option key={service.id} value={service.id}>{isArabic ? service.nameAr : service.nameEn}</option>)}</select><Input required type="number" min="0" step="0.01" placeholder={isArabic ? "السعر في هذا الفرع" : "Price at this branch"} value={priceForm.price} onChange={event => setPriceForm(current => ({ ...current, price: event.target.value }))} /><Button disabled={savePrice.isPending} className="w-fit bg-slate-950 text-white hover:bg-slate-800">{savePrice.isPending ? (isArabic ? "جارٍ الحفظ..." : "Saving...") : (isArabic ? "حفظ سعر الفرع" : "Save branch price")}</Button>{savePrice.error && <p className="text-sm text-red-600">{isArabic ? "تعذر حفظ سعر الفرع." : "Could not save the branch price."}</p>}</form>{priceForm.branchId && <div className="mt-4 space-y-2">{(branchServices.data ?? []).map(item => <div key={item.service.id} className="flex items-center justify-between rounded-lg bg-slate-50 p-3 text-sm"><span>{isArabic ? item.service.nameAr : item.service.nameEn} <small className={item.branchService.isActive ? "text-emerald-700" : "text-slate-400"}>({item.branchService.isActive ? (isArabic ? "نشط" : "Active") : (isArabic ? "متوقف" : "Inactive")})</small></span><div className="flex items-center gap-2"><strong>{item.branchService.price} EGP</strong><Button type="button" size="sm" variant="outline" onClick={() => savePrice.mutate({ branchId: Number(priceForm.branchId), serviceId: item.service.id, price: String(item.branchService.price), isActive: !item.branchService.isActive })}>{item.branchService.isActive ? (isArabic ? "إيقاف" : "Deactivate") : (isArabic ? "تفعيل" : "Activate")}</Button></div></div>)}</div>}</CardContent></Card></div>

  <Card className="border-0 bg-white"><CardHeader><CardTitle>{isArabic ? "قائمة الخدمات" : "Service directory"}</CardTitle></CardHeader><CardContent>{services.isLoading ? <p className="text-sm text-slate-400">{isArabic ? "جارٍ التحميل..." : "Loading..."}</p> : <div className="space-y-2">{(services.data ?? []).map(service => <div key={service.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-slate-100 p-3"><div><p className="font-medium">{isArabic ? service.nameAr : service.nameEn}</p><p className="text-xs text-slate-400">{isArabic ? "السعر الافتراضي" : "Default price"}: {service.defaultPrice} EGP</p></div><div className="flex gap-2"><Button size="sm" variant="ghost" onClick={() => { setEditingServiceId(service.id); setServiceForm({ nameAr: service.nameAr, nameEn: service.nameEn, defaultPrice: String(service.defaultPrice) }); }}>{isArabic ? "تعديل" : "Edit"}</Button><Button size="sm" variant="outline" onClick={() => update.mutate({ id: service.id, isActive: !service.isActive })}>{service.isActive ? (isArabic ? "إيقاف" : "Deactivate") : (isArabic ? "تفعيل" : "Activate")}</Button></div></div>)}</div>}</CardContent></Card></div></div></DashboardLayout>;
}
