import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { useLanguage } from "@/contexts/LanguageContext";
import { trpc } from "@/lib/trpc";
import { Plus, UserCog, X } from "lucide-react";
import { useEffect, useState } from "react";

const roles = ["branch_manager", "doctor", "receptionist", "accountant"] as const;
const roleLabel = (role: string, ar: boolean) => ({ branch_manager: ar ? "مدير فرع" : "Branch manager", doctor: ar ? "طبيب" : "Doctor", receptionist: ar ? "استقبال" : "Receptionist", accountant: ar ? "حسابات" : "Accountant", super_admin: ar ? "مدير رئيسي" : "Super admin" }[role] ?? role);

type EditingUser = { id: number; name: string; email: string; username: string; role: string };

export default function UsersPage() {
  const { isArabic, direction } = useLanguage();
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState({ name: "", email: "", username: "", password: "", role: "doctor" as typeof roles[number] });
  const [editing, setEditing] = useState<EditingUser | null>(null);
  const [editingBranchIds, setEditingBranchIds] = useState<number[]>([]);
  const users = trpc.users.list.useQuery();
  const branches = trpc.branches.list.useQuery();
  const userBranches = trpc.users.branches.useQuery({ userId: editing?.id ?? 0 }, { enabled: Boolean(editing?.id) });
  const create = trpc.users.create.useMutation({ onSuccess: () => { setOpen(false); void users.refetch(); setForm({ name: "", email: "", username: "", password: "", role: "doctor" }); } });
  const updateAccount = trpc.users.update.useMutation({ onSuccess: () => void users.refetch() });
  const resetPassword = trpc.users.resetPassword.useMutation({ onSuccess: () => void users.refetch() });

  useEffect(() => { if (editing && userBranches.data) setEditingBranchIds(userBranches.data); }, [editing, userBranches.data]);

  const updateForm = (key: keyof typeof form, value: string) => setForm(current => ({ ...current, [key]: value }));
  const toggleAccount = (id: number, isActive: boolean) => updateAccount.mutate({ id, isActive: !isActive });
  const changePassword = (id: number) => { const password = window.prompt(isArabic ? "أدخل كلمة المرور الجديدة (8 أحرف على الأقل)" : "Enter a new password (at least 8 characters)"); if (password) resetPassword.mutate({ id, password }); };
  const saveEdit = async (event: React.FormEvent) => { event.preventDefault(); if (!editing) return; try { await updateAccount.mutateAsync({ id: editing.id, name: editing.name, email: editing.email, username: editing.username, role: editing.role as "super_admin" | "branch_manager" | "doctor" | "receptionist" | "accountant", branchIds: editingBranchIds }); setEditing(null); } catch { /* mutation errors are shown below */ } };

  return <DashboardLayout><div dir={direction} className="min-h-screen bg-[#f7fafc] p-4 text-slate-900 sm:p-8"><div className="mx-auto max-w-6xl space-y-6">
    <header className="flex flex-col gap-4 border-b border-slate-200 pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-teal-700">{isArabic ? "إدارة الصلاحيات" : "Access management"}</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">{isArabic ? "المستخدمون" : "Users"}</h1><p className="mt-2 text-sm text-slate-500">{isArabic ? "إنشاء حسابات الموظفين وتحديد أدوارهم وفروعهم." : "Create staff accounts and assign roles and branches."}</p></div><Button onClick={() => setOpen(true)} className="gap-2 bg-slate-950 text-white hover:bg-slate-800"><Plus className="h-4 w-4" />{isArabic ? "إضافة مستخدم" : "Add user"}</Button></header>
    {open && <Card className="border-teal-100 bg-white"><CardHeader className="flex flex-row items-center justify-between"><CardTitle>{isArabic ? "حساب موظف جديد" : "New staff account"}</CardTitle><Button variant="ghost" size="icon" onClick={() => setOpen(false)}><X className="h-4 w-4" /></Button></CardHeader><CardContent><form onSubmit={event => { event.preventDefault(); create.mutate(form); }} className="grid gap-4 md:grid-cols-2"><Input required placeholder={isArabic ? "الاسم الكامل" : "Full name"} value={form.name} onChange={event => updateForm("name", event.target.value)} /><Input required type="email" placeholder={isArabic ? "البريد الإلكتروني" : "Email"} value={form.email} onChange={event => updateForm("email", event.target.value)} /><Input required placeholder={isArabic ? "اسم المستخدم" : "Username"} value={form.username} onChange={event => updateForm("username", event.target.value)} /><Input required type="password" minLength={8} placeholder={isArabic ? "كلمة المرور" : "Password"} value={form.password} onChange={event => updateForm("password", event.target.value)} /><select className="h-10 rounded-md border border-slate-200 bg-white px-3 text-sm" value={form.role} onChange={event => updateForm("role", event.target.value)}>{roles.map(role => <option key={role} value={role}>{roleLabel(role, isArabic)}</option>)}</select><Button type="submit" disabled={create.isPending} className="bg-teal-700 text-white hover:bg-teal-800">{create.isPending ? (isArabic ? "جارٍ الحفظ..." : "Saving...") : (isArabic ? "حفظ الحساب" : "Save account")}</Button></form>{create.error && <p className="mt-3 text-sm text-red-600">{isArabic ? "تعذر إنشاء الحساب. قد يكون اسم المستخدم مستخدمًا." : "Could not create account. The username may already exist."}</p>}</CardContent></Card>}
    {editing && <Card className="border-teal-100 bg-white"><CardHeader className="flex flex-row items-center justify-between"><CardTitle>{isArabic ? "تعديل بيانات المستخدم" : "Edit user"}</CardTitle><Button variant="ghost" size="icon" onClick={() => setEditing(null)}><X className="h-4 w-4" /></Button></CardHeader><CardContent><form onSubmit={saveEdit} className="grid gap-4 md:grid-cols-2"><Input required value={editing.name} onChange={event => setEditing(current => current ? { ...current, name: event.target.value } : current)} placeholder={isArabic ? "الاسم" : "Name"} /><Input required type="email" value={editing.email} onChange={event => setEditing(current => current ? { ...current, email: event.target.value } : current)} placeholder={isArabic ? "البريد" : "Email"} /><Input required value={editing.username} onChange={event => setEditing(current => current ? { ...current, username: event.target.value } : current)} placeholder={isArabic ? "اسم المستخدم" : "Username"} /><select className="h-10 rounded-md border border-slate-200 bg-white px-3 text-sm" value={editing.role} onChange={event => setEditing(current => current ? { ...current, role: event.target.value } : current)}>{["super_admin", ...roles].map(role => <option key={role} value={role}>{roleLabel(role, isArabic)}</option>)}</select><select multiple aria-label={isArabic ? "فروع المستخدم" : "User branches"} className="min-h-24 rounded-md border border-slate-200 bg-white px-3 py-2 text-sm" value={editingBranchIds.map(String)} onChange={event => setEditingBranchIds(Array.from(event.target.selectedOptions).map(option => Number(option.value)))}>{(branches.data ?? []).map(branch => <option key={branch.id} value={branch.id}>{isArabic ? branch.nameAr : branch.nameEn}</option>)}</select>{updateAccount.error && <p className="text-sm text-red-600 md:col-span-2">{isArabic ? "تعذر حفظ بيانات المستخدم أو تعيينات الفروع. لم يتم تطبيق التعديل." : "Could not save the user or branch assignments. No changes were applied."}</p>}<Button type="submit" disabled={updateAccount.isPending} className="bg-teal-700 text-white hover:bg-teal-800">{updateAccount.isPending ? (isArabic ? "جارٍ الحفظ..." : "Saving...") : (isArabic ? "حفظ التعديل" : "Save changes")}</Button></form></CardContent></Card>}
    <Card className="border-0 bg-white shadow-[0_12px_35px_rgba(15,23,42,0.05)]"><CardHeader><CardTitle>{isArabic ? "حسابات النظام" : "System accounts"}</CardTitle></CardHeader><CardContent>{users.isLoading ? <p className="p-6 text-sm text-slate-400">{isArabic ? "جارٍ التحميل..." : "Loading..."}</p> : (users.data ?? []).length === 0 ? <div className="flex min-h-[160px] flex-col items-center justify-center text-center text-slate-400"><UserCog className="mb-3 h-8 w-8" /><p>{isArabic ? "لا توجد حسابات داخلية بعد" : "No internal accounts yet"}</p></div> : <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-sm"><thead><tr className="border-b border-slate-100 text-right text-slate-400"><th className="px-3 py-3">{isArabic ? "الاسم" : "Name"}</th><th className="px-3 py-3">{isArabic ? "اسم المستخدم" : "Username"}</th><th className="px-3 py-3">{isArabic ? "الدور" : "Role"}</th><th className="px-3 py-3">{isArabic ? "الحالة" : "Status"}</th><th className="px-3 py-3">{isArabic ? "إجراءات" : "Actions"}</th></tr></thead><tbody>{(users.data ?? []).map(account => <tr key={account.id} className="border-b border-slate-50"><td className="px-3 py-4 font-medium">{account.name}</td><td className="px-3 py-4 text-slate-500">{account.username}</td><td className="px-3 py-4"><Badge variant="outline">{roleLabel(account.role, isArabic)}</Badge></td><td className="px-3 py-4 text-emerald-700">{account.isActive ? (isArabic ? "نشط" : "Active") : (isArabic ? "متوقف" : "Inactive")}</td><td className="flex gap-2 px-3 py-3"><Button size="sm" variant="ghost" onClick={() => { setEditing({ id: account.id, name: account.name ?? "", email: account.email ?? "", username: account.username ?? "", role: account.role }); setEditingBranchIds([]); }}>{isArabic ? "تعديل" : "Edit"}</Button><Button size="sm" variant="outline" onClick={() => toggleAccount(account.id, account.isActive)}>{account.isActive ? (isArabic ? "إيقاف" : "Deactivate") : (isArabic ? "تفعيل" : "Activate")}</Button><Button size="sm" variant="ghost" onClick={() => changePassword(account.id)}>{isArabic ? "كلمة مرور" : "Password"}</Button></td></tr>)}</tbody></table></div>}</CardContent></Card>
  </div></div></DashboardLayout>;
}
